services:
  pyredis-engine:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pyredis-engine
    ports:
      - "6379:6379"
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - pyredis-data:/app/data
    restart: unless-stopped

  pyredis-dashboard:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pyredis-dashboard
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - pyredis-engine
    restart: unless-stopped

volumes:
  pyredis-data:
    driver: local
